<?php

/**
 * This function changes the button text on system site configuation 
 *
 * @param      <type>                               $form        The form
 * @param      Drupal\Core\Form\FormStateInterface  $form_state  The form state
 * @param      string                               $form_id     The form identifier
 */

function mymodule_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	
	 if($form_id == 'system_site_information_settings') {
    	$form['actions']['submit']['#value'] = 'Update Configuration';
	}
}
